"""
Background Thread System - Separated characters live their own stories.

"While you're not looking, the world keeps turning."

When a character is separated from the main party:
- They face real situations generated by the DM
- They make real decisions based on their alignment/personality
- Combat is real, consequences are real
- Their journal tracks everything
- When reunited, they have genuine history

This is NOT "the DM summarizes what probably happened."
This IS the character actually living through events.

FULL SIMULATION MODE:
- Characters get the SAME systems as the player
- Opening matrix rolled at separation provides context
- DM Council (Advocate/Adversary/Judge) deliberates decisions
- Real inventory tracking (can find/lose items)
- Real condition tracking (hunger, thirst, injuries)
- Real fatigue tracking (must sleep eventually)
- Weather/time synced with world state
"""

import random
from typing import Dict, List, Optional, Any, Callable
from datetime import datetime, timedelta
from dataclasses import dataclass
from enum import Enum
import asyncio

from autopilot import (
    PlayerCharacter, AutopilotTracker, get_autopilot_tracker,
    Alignment, Drive, Priority, JournalEntry
)
import debug_logger as dbg

# === TRACKER IMPORTS FOR FULL SIMULATION ===
try:
    from inventory import get_inventory_tracker, Item, ItemCategory
    HAS_INVENTORY = True
except ImportError:
    HAS_INVENTORY = False
    dbg.warn("background", "Inventory tracker not available")

try:
    from condition_tracker import (
        get_condition_tracker, OverallCondition, HungerStatus,
        ThirstStatus, InjurySeverity, Injury
    )
    HAS_CONDITION = True
except ImportError:
    HAS_CONDITION = False
    dbg.warn("background", "Condition tracker not available")

try:
    from fatigue import get_fatigue_tracker, FatigueLevel
    HAS_FATIGUE = True
except ImportError:
    HAS_FATIGUE = False
    dbg.warn("background", "Fatigue tracker not available")


class SituationType(Enum):
    """Types of situations a separated character might face."""
    SCAVENGE = "scavenge"           # Finding supplies
    SHELTER = "shelter"             # Finding/maintaining shelter
    ENCOUNTER_HOSTILE = "hostile"   # Combat or dangerous encounter
    ENCOUNTER_NEUTRAL = "neutral"   # Meeting someone uncertain
    ENCOUNTER_FRIENDLY = "friendly" # Meeting potential allies
    ENVIRONMENTAL = "environmental" # Weather, terrain, natural hazards
    DISCOVERY = "discovery"         # Finding something interesting
    REST = "rest"                   # Quiet moment, recovery
    MORAL_DILEMMA = "dilemma"       # Choice that tests character


# Situation weights by drive - what situations is each drive likely to create?
DRIVE_SITUATION_WEIGHTS = {
    Drive.SURVIVAL: {
        SituationType.SCAVENGE: 3,
        SituationType.SHELTER: 2,
        SituationType.ENCOUNTER_HOSTILE: 2,
        SituationType.ENVIRONMENTAL: 2,
        SituationType.REST: 1,
    },
    Drive.SAFETY: {
        SituationType.SHELTER: 3,
        SituationType.SCAVENGE: 2,
        SituationType.ENCOUNTER_NEUTRAL: 2,
        SituationType.REST: 2,
        SituationType.ENVIRONMENTAL: 1,
    },
    Drive.BELONGING: {
        SituationType.ENCOUNTER_FRIENDLY: 3,
        SituationType.ENCOUNTER_NEUTRAL: 2,
        SituationType.MORAL_DILEMMA: 2,
        SituationType.DISCOVERY: 1,
        SituationType.REST: 1,
    },
    Drive.ESTEEM: {
        SituationType.ENCOUNTER_HOSTILE: 2,
        SituationType.DISCOVERY: 2,
        SituationType.MORAL_DILEMMA: 2,
        SituationType.ENCOUNTER_NEUTRAL: 2,
        SituationType.SCAVENGE: 1,
    },
    Drive.MEANING: {
        SituationType.DISCOVERY: 3,
        SituationType.MORAL_DILEMMA: 2,
        SituationType.ENCOUNTER_FRIENDLY: 2,
        SituationType.ENCOUNTER_NEUTRAL: 1,
        SituationType.REST: 1,
    },
}


@dataclass
class BackgroundSituation:
    """A situation generated for a separated character."""
    situation_type: SituationType
    description: str
    options: List[str]  # Possible responses
    difficulty: int  # 1-10, affects outcomes
    potential_rewards: List[str]
    potential_risks: List[str]
    time_pressure: bool  # Must act quickly?


@dataclass
class BackgroundTickResult:
    """Result of processing a background tick for a character."""
    character_id: str
    character_name: str
    situation: BackgroundSituation
    response: str  # What the character did
    outcome: str  # What happened
    condition_change: Optional[str]
    supplies_change: Optional[str]
    morale_change: Optional[str]
    discovery: Optional[str]
    encounter_survived: bool
    new_ally: Optional[str]
    new_enemy: Optional[str]


class BackgroundTickProcessor:
    """
    Processes background ticks for separated characters.

    Each tick:
    1. Generates a situation based on character's drive and world state
    2. Asks the character's model to respond
    3. Resolves the outcome
    4. Updates character state
    5. Logs to journal
    """

    def __init__(
        self,
        tracker: AutopilotTracker = None,
        ollama_generate: Callable = None,
        dm_generate: Callable = None,
    ):
        self.tracker = tracker or get_autopilot_tracker()
        self.ollama_generate = ollama_generate  # For character responses
        self.dm_generate = dm_generate  # For situation generation and resolution

    async def process_tick(
        self,
        character: PlayerCharacter,
        world_context: str,
        threat_type: str = "",
        world_state: str = "",
        interval_minutes: int = 30,
        room_id: str = "",
    ) -> Optional[BackgroundTickResult]:
        """
        Process a single background tick for a separated character.

        FULL SIMULATION MODE: This character gets the SAME systems as the player:
        - Opening matrix context from separation
        - DM Council deliberates decisions (MEDIUM/MAJOR)
        - Real inventory updates
        - Real condition progression (hunger/thirst/injuries)
        - Real fatigue progression

        Args:
            character: The separated character
            world_context: Description of the world/scenario
            threat_type: What kind of threats exist
            world_state: Current state of civilization
            interval_minutes: Time elapsed - affects event drama:
                < 5 min: Mundane (resting, small observations)
                5-30 min: Minor (found something, brief encounter)
                30-60 min: Meaningful (decisions, discoveries)
                60+ min: Major (combat, significant changes)
            room_id: Room ID for tracker access
        """
        if not character.is_separated or not character.is_alive:
            return None

        # === RICH DEBUG OUTPUT: FULL SIMULATION TICK ===
        print(f"\n{'='*70}")
        print(f"  FULL SIMULATION TICK: {character.character_name.upper()}")
        print(f"{'='*70}")
        print(f"  Time elapsed: {interval_minutes} minutes ({interval_minutes/60:.1f} hours)")
        print(f"  Location: {character.last_known_location or 'Unknown'}")
        print(f"  Current state: {character.condition} | Supplies: {character.supplies_status} | Morale: {character.morale}")

        # === FULL SIMULATION: PROGRESS TIME-BASED SYSTEMS ===
        hours_elapsed = interval_minutes / 60.0
        character.hours_since_separation = getattr(character, 'hours_since_separation', 0) + hours_elapsed
        print(f"  Hours since separation: {character.hours_since_separation:.1f}h")

        # Progress hunger/thirst/fatigue based on elapsed time
        print(f"\n  [TIME PROGRESSION]")
        self._progress_condition_over_time(character, hours_elapsed, room_id)
        self._progress_fatigue_over_time(character, hours_elapsed, room_id)

        # Get matrix context for richer situation generation
        matrix_context = self._get_matrix_context(character)
        if matrix_context:
            print(f"\n  [MATRIX CONTEXT]")
            for line in matrix_context.split('\n'):
                print(f"    {line}")

        # Build enriched world context with matrix info
        enriched_context = world_context
        if matrix_context:
            enriched_context = f"{world_context}\n\n=== CHARACTER'S CURRENT SITUATION ===\n{matrix_context}"

        # 1. Generate a situation (drama scales with interval)
        print(f"\n  [GENERATING SITUATION...]")
        situation = await self._generate_situation(
            character, enriched_context, threat_type, world_state, interval_minutes
        )
        print(f"\n  [SITUATION GENERATED]")
        print(f"    Type: {situation.situation_type.value.upper()}")
        print(f"    Difficulty: {situation.difficulty}/10")
        print(f"    Time pressure: {'YES' if situation.time_pressure else 'No'}")
        print(f"    Description: {situation.description[:200]}...")
        print(f"    Options:")
        for i, opt in enumerate(situation.options, 1):
            print(f"      {i}. {opt}")

        # 2. Get character's response
        print(f"\n  [CHARACTER DECIDING...]")
        response = await self._get_character_response(character, situation)
        print(f"\n  [CHARACTER RESPONSE]")
        print(f"    {response[:300]}...")

        # 3. Resolve the outcome using DM Council for meaningful decisions
        print(f"\n  [COUNCIL DELIBERATION...]")
        result = await self._resolve_outcome_with_council(
            character, situation, response, enriched_context, room_id
        )
        print(f"\n  [OUTCOME]")
        print(f"    {result.outcome[:300]}...")
        if result.condition_change:
            print(f"    Condition change: {result.condition_change}")
        if result.supplies_change:
            print(f"    Supplies change: {result.supplies_change}")
        if result.morale_change:
            print(f"    Morale change: {result.morale_change}")
        if result.discovery:
            print(f"    Discovery: {result.discovery}")

        # 4. Update character state (with real tracker integration)
        print(f"\n  [APPLYING RESULTS TO TRACKERS...]")
        self._apply_result(character, result, room_id)

        # 5. Mark tick as processed
        character.record_background_tick()
        # Expand search radius based on actual interval
        hours_elapsed = interval_minutes / 60.0
        character.expand_search_radius(hours_elapsed=hours_elapsed)

        print(f"\n  [TICK COMPLETE]")
        print(f"    New state: {character.condition} | Supplies: {character.supplies_status} | Morale: {character.morale}")
        print(f"    Search radius: {character.search_radius_km:.1f} km")
        print(f"{'='*70}\n")

        return result

    # ==========================================================================
    # FULL SIMULATION HELPER METHODS
    # ==========================================================================

    def _get_matrix_context(self, character: PlayerCharacter) -> str:
        """Extract context from the character's separation matrix."""
        matrix = getattr(character, 'separation_matrix', {})
        if not matrix:
            return ""

        parts = []

        # Weather and time
        weather = matrix.get('weather', {})
        if weather:
            parts.append(f"Weather: {weather.get('description', 'unknown')}")

        time_of_day = matrix.get('time_of_day', character.current_time_of_day)
        if time_of_day:
            parts.append(f"Time: {time_of_day}")

        # Tension type affects what situations arise
        tension = matrix.get('tension_type', {})
        if tension:
            parts.append(f"Current tension: {tension.get('label', 'unknown')} - {tension.get('effects', '')}")

        # Environmental features
        env = matrix.get('environmental_feature', {})
        if env:
            parts.append(f"Environment: {env.get('label', '')} - {env.get('description', '')}")

        # Threat level
        threat = matrix.get('threat_level', {})
        if threat:
            parts.append(f"Threat level: {threat.get('label', 'unknown')}")

        # Resources
        resources = matrix.get('resources', {})
        if resources:
            parts.append(f"Local resources: {resources.get('label', 'unknown')} - {resources.get('description', '')}")

        # Hours since separation
        hours = getattr(character, 'hours_since_separation', 0)
        if hours > 0:
            parts.append(f"Hours separated: {hours:.1f}")

        return "\n".join(parts)

    def _progress_condition_over_time(self, character: PlayerCharacter, hours_elapsed: float, room_id: str):
        """Progress hunger and thirst based on time elapsed."""
        if not HAS_CONDITION or not room_id:
            print(f"    Condition tracking: Not available")
            return

        try:
            condition_tracker = get_condition_tracker()
            char_id = f"sep_{character.player_id}"
            char_condition = condition_tracker.get_or_create(char_id)

            if not char_condition:
                return

            # Hunger progresses roughly every 6 hours
            # Thirst progresses roughly every 4 hours
            hunger_progress = hours_elapsed / 6.0
            thirst_progress = hours_elapsed / 4.0

            # Accumulate and check thresholds
            char_condition.hunger_accumulator = getattr(char_condition, 'hunger_accumulator', 0) + hunger_progress
            char_condition.thirst_accumulator = getattr(char_condition, 'thirst_accumulator', 0) + thirst_progress

            print(f"    Hunger: {char_condition.hunger.value} (accumulator: {char_condition.hunger_accumulator:.2f}/1.0)")
            print(f"    Thirst: {char_condition.thirst.value} (accumulator: {char_condition.thirst_accumulator:.2f}/1.0)")

            # Worsen hunger if accumulated enough
            if char_condition.hunger_accumulator >= 1.0:
                old_hunger = char_condition.hunger
                char_condition.hunger = char_condition.hunger.worsen()
                char_condition.hunger_accumulator -= 1.0
                if char_condition.hunger != old_hunger:
                    print(f"    >>> HUNGER WORSENED: {old_hunger.value} -> {char_condition.hunger.value}")
                    character.add_journal_entry(
                        event_type="condition",
                        description=f"Condition changed: {old_hunger.value} → {char_condition.hunger.value}",
                        severity="minor",
                    )

            # Worsen thirst if accumulated enough
            if char_condition.thirst_accumulator >= 1.0:
                old_thirst = char_condition.thirst
                char_condition.thirst = char_condition.thirst.worsen()
                char_condition.thirst_accumulator -= 1.0
                if char_condition.thirst != old_thirst:
                    print(f"    >>> THIRST WORSENED: {old_thirst.value} -> {char_condition.thirst.value}")
                    character.add_journal_entry(
                        event_type="condition",
                        description=f"Thirst: {old_thirst.value} → {char_condition.thirst.value}",
                        severity="minor",
                    )

            condition_tracker._save()

        except Exception as e:
            print(f"    Condition tracking error: {e}")

    def _progress_fatigue_over_time(self, character: PlayerCharacter, hours_elapsed: float, room_id: str):
        """Progress fatigue based on time elapsed."""
        if not HAS_FATIGUE or not room_id:
            print(f"    Fatigue tracking: Not available")
            return

        try:
            fatigue_tracker = get_fatigue_tracker()
            char_id = f"sep_{character.player_id}"
            char_fatigue = fatigue_tracker.get_or_create_fatigue(char_id, character.character_name)

            if not char_fatigue:
                return

            # Add hours awake
            old_level = char_fatigue.fatigue_level
            char_fatigue.hours_awake += hours_elapsed
            char_fatigue.hours_since_rest += hours_elapsed

            print(f"    Fatigue: {old_level.value} ({char_fatigue.hours_awake:.1f}h awake)")

            # Recalculate fatigue level based on hours awake
            new_level = FatigueLevel.RESTED
            if char_fatigue.hours_awake >= 48:
                new_level = FatigueLevel.CRITICAL
            elif char_fatigue.hours_awake >= 36:
                new_level = FatigueLevel.DEPLETED
            elif char_fatigue.hours_awake >= 24:
                new_level = FatigueLevel.EXHAUSTED
            elif char_fatigue.hours_awake >= 18:
                new_level = FatigueLevel.TIRED
            elif char_fatigue.hours_awake >= 12:
                new_level = FatigueLevel.FINE

            char_fatigue.fatigue_level = new_level

            if new_level != old_level:
                print(f"    >>> FATIGUE CHANGED: {old_level.value} -> {new_level.value}")
                character.add_journal_entry(
                    event_type="condition",
                    description=f"Fatigue: {old_level.value} → {new_level.value} ({char_fatigue.hours_awake:.1f}h awake)",
                    severity="minor" if new_level.value in ["fine", "tired"] else "notable",
                )

            fatigue_tracker._save()

        except Exception as e:
            print(f"    Fatigue tracking error: {e}")

    async def _resolve_outcome_with_council(
        self,
        character: PlayerCharacter,
        situation: BackgroundSituation,
        response: str,
        context: str,
        room_id: str,
    ) -> BackgroundTickResult:
        """
        Resolve the outcome using DM Council for meaningful decisions.

        FULL SIMULATION: Same council system as the player uses.
        - MINOR situations: Quick resolution
        - MEDIUM situations: Advocate vs Adversary, Judge decides
        - MAJOR situations: Full council deliberation
        """
        # Determine stakes based on situation difficulty and type
        if situation.difficulty <= 3:
            stakes = "MINOR"
        elif situation.difficulty <= 6:
            stakes = "MEDIUM"
        else:
            stakes = "MAJOR"

        # Life-threatening situations are always MAJOR
        if situation.situation_type in (SituationType.ENCOUNTER_HOSTILE,) and situation.difficulty >= 5:
            stakes = "MAJOR"

        # Rich debug output for stakes determination
        print(f"\n    [COUNCIL] Stakes: {stakes} (difficulty {situation.difficulty}/10)")

        if stakes == "MINOR":
            # Quick resolution without full council
            print(f"    [COUNCIL] MINOR stakes - quick resolution (no debate)")
            return await self._resolve_outcome(character, situation, response)

        # === MEDIUM/MAJOR: Run the Council ===
        tension = f"Will {character.character_name} {self._get_tension_description(situation)}?"
        print(f"    [COUNCIL] Core tension: {tension}")

        if not self.dm_generate:
            print(f"    [COUNCIL] No dm_generate available - falling back")
            return await self._resolve_outcome(character, situation, response)

        try:
            # Get Advocate's argument (FOR success)
            advocate_prompt = f"""You are the ADVOCATE arguing FOR {character.character_name} succeeding.

CONTEXT:
{context}

SITUATION: {situation.description}
CHARACTER'S ACTION: {response}
CORE TENSION: {tension}

Consider:
- Character's skills: {character.get_skills_string()}
- Character's condition: {character.condition}
- Available resources: {situation.potential_rewards}

Argue in 2-3 sentences why they should SUCCEED. Be specific about advantages."""

            advocate = await self.dm_generate(advocate_prompt)
            print(f"\n    [ADVOCATE] (arguing FOR success)")
            print(f"    {'-'*50}")
            for line in advocate.strip().split('\n'):
                print(f"      {line}")
            print(f"    {'-'*50}")

            # Get Adversary's argument (AGAINST/complications)
            adversary_prompt = f"""You are the ADVERSARY arguing for COMPLICATIONS for {character.character_name}.

CONTEXT:
{context}

SITUATION: {situation.description}
CHARACTER'S ACTION: {response}
CORE TENSION: {tension}

Consider:
- Difficulty: {situation.difficulty}/10
- Risks: {situation.potential_risks}
- Character's weaknesses or condition: {character.condition}

Argue in 2-3 sentences for realistic COMPLICATIONS. Don't be unfair, but don't be soft.
If there's genuinely no reasonable complication, concede."""

            adversary = await self.dm_generate(adversary_prompt)
            print(f"\n    [ADVERSARY] (arguing for COMPLICATIONS)")
            print(f"    {'-'*50}")
            for line in adversary.strip().split('\n'):
                print(f"      {line}")
            print(f"    {'-'*50}")

            # Get Judge's ruling
            judge_prompt = f"""You are the JUDGE. Two advocates have argued about {character.character_name}'s situation.

SITUATION: {situation.description}
ACTION TAKEN: {response}
TENSION: {tension}

ADVOCATE (for success): {advocate}
ADVERSARY (for complications): {adversary}

Weigh both arguments fairly. Consider:
- Is the Advocate's reasoning sound?
- Is the Adversary's complication plausible or reaching?
- What's the most narratively interesting outcome?

DELIVER YOUR RULING:
OUTCOME: [SUCCESS/PARTIAL/FAILURE]
RULING: [2-3 sentence description of what happens]
COST: [Any price paid, injury, resource used, or "None"]"""

            ruling = await self.dm_generate(judge_prompt)
            print(f"\n    [JUDGE] RULING")
            print(f"    {'='*50}")
            for line in ruling.strip().split('\n'):
                print(f"      {line}")
            print(f"    {'='*50}")

            # Parse the ruling
            return self._parse_council_ruling(character, situation, response, ruling, stakes)

        except Exception as e:
            print(f"\n    [COUNCIL ERROR] {e} - falling back to simple resolution")
            return await self._resolve_outcome(character, situation, response)

    def _get_tension_description(self, situation: BackgroundSituation) -> str:
        """Get a tension description based on situation type."""
        tension_map = {
            SituationType.SCAVENGE: "find useful supplies",
            SituationType.SHELTER: "find safe shelter",
            SituationType.ENCOUNTER_HOSTILE: "survive this encounter",
            SituationType.ENCOUNTER_NEUTRAL: "handle this stranger safely",
            SituationType.ENCOUNTER_FRIENDLY: "make a connection",
            SituationType.ENVIRONMENTAL: "overcome the environmental hazard",
            SituationType.DISCOVERY: "learn something valuable",
            SituationType.REST: "rest safely",
            SituationType.MORAL_DILEMMA: "make the right choice",
        }
        return tension_map.get(situation.situation_type, "succeed in this moment")

    def _parse_council_ruling(
        self,
        character: PlayerCharacter,
        situation: BackgroundSituation,
        response: str,
        ruling_text: str,
        stakes: str,
    ) -> BackgroundTickResult:
        """Parse the council's ruling into a BackgroundTickResult."""
        outcome = "PARTIAL"
        ruling = ""
        cost = ""

        for line in ruling_text.strip().split('\n'):
            line = line.strip()
            if line.startswith("OUTCOME:"):
                o = line.replace("OUTCOME:", "").strip().upper()
                if o in ["SUCCESS", "PARTIAL", "FAILURE"]:
                    outcome = o
            elif line.startswith("RULING:"):
                ruling = line.replace("RULING:", "").strip()
            elif line.startswith("COST:"):
                cost = line.replace("COST:", "").strip()

        # Determine condition/supply changes based on outcome
        condition_change = None
        supplies_change = None
        morale_change = None
        discovery = None

        if outcome == "SUCCESS":
            morale_change = "up"
            if situation.situation_type == SituationType.SCAVENGE:
                supplies_change = "found supplies"
            if situation.situation_type == SituationType.DISCOVERY:
                discovery = ruling[:100] if ruling else "Made an important discovery"
            if situation.situation_type == SituationType.REST:
                condition_change = "rested"  # Will be interpreted as improvement

        elif outcome == "FAILURE":
            morale_change = "down"
            if situation.situation_type == SituationType.ENCOUNTER_HOSTILE:
                condition_change = "injured"
            if cost and "injur" in cost.lower():
                condition_change = "injured"

        elif outcome == "PARTIAL":
            # Partial success - some gain, some cost
            if situation.situation_type == SituationType.SCAVENGE and "found" in ruling.lower():
                supplies_change = "found some supplies"
            if cost and "injur" in cost.lower():
                condition_change = "injured"

        # Build the outcome description
        full_outcome = ruling
        if cost and cost.lower() not in ["none", "n/a", ""]:
            full_outcome += f" [{cost}]"

        return BackgroundTickResult(
            character_id=character.player_id,
            character_name=character.character_name,
            situation=situation,
            response=response,
            outcome=full_outcome or ruling_text[:200],
            condition_change=condition_change,
            supplies_change=supplies_change,
            morale_change=morale_change,
            discovery=discovery,
            encounter_survived=situation.situation_type == SituationType.ENCOUNTER_HOSTILE and outcome != "FAILURE",
            new_ally=None,  # Could parse from ruling
            new_enemy=None,
        )

    async def _generate_situation(
        self,
        character: PlayerCharacter,
        world_context: str,
        threat_type: str,
        world_state: str,
        interval_minutes: int = 30,
    ) -> BackgroundSituation:
        """Generate a situation for the character to face."""

        # Determine drama level based on interval
        # Short intervals = mundane life, long intervals = major events
        if interval_minutes < 5:
            drama_level = "mundane"
            drama_guidance = "A quiet, everyday moment. Small observation, brief rest, minor task. Nothing dramatic."
            allowed_types = [SituationType.REST, SituationType.SCAVENGE, SituationType.SHELTER]
            max_difficulty = 3
        elif interval_minutes < 30:
            drama_level = "minor"
            drama_guidance = "A small but meaningful moment. Brief encounter, minor discovery, simple choice."
            allowed_types = [SituationType.REST, SituationType.SCAVENGE, SituationType.SHELTER,
                           SituationType.DISCOVERY, SituationType.ENCOUNTER_NEUTRAL]
            max_difficulty = 5
        elif interval_minutes < 60:
            drama_level = "meaningful"
            drama_guidance = "A significant event. Real decision, notable discovery, challenging situation."
            allowed_types = list(SituationType)  # All types available
            max_difficulty = 7
        else:
            drama_level = "major"
            drama_guidance = "A pivotal moment. Combat, life-changing choice, major discovery, real consequences."
            allowed_types = list(SituationType)
            max_difficulty = 10

        # Choose situation type based on drive, filtered by drama level
        weights = DRIVE_SITUATION_WEIGHTS.get(character.current_drive, {})
        if not weights:
            weights = {SituationType.SCAVENGE: 1, SituationType.REST: 1}

        # Filter to allowed types for this drama level
        filtered_weights = {k: v for k, v in weights.items() if k in allowed_types}
        if not filtered_weights:
            filtered_weights = {allowed_types[0]: 1}

        situation_types = list(filtered_weights.keys())
        situation_weights = list(filtered_weights.values())
        situation_type = random.choices(situation_types, weights=situation_weights)[0]

        # Adjust based on condition
        if character.condition in ["injured", "critical"]:
            if random.random() < 0.4 and SituationType.REST in allowed_types:
                situation_type = SituationType.REST
        elif character.supplies_status in ["critical", "none"]:
            if random.random() < 0.5 and SituationType.SCAVENGE in allowed_types:
                situation_type = SituationType.SCAVENGE

        # Generate the situation using DM
        if self.dm_generate:
            prompt = f"""Generate a survival situation for a separated character.

Character: {character.character_name}
Current condition: {character.condition}
Supplies: {character.supplies_status}
Morale: {character.morale}
Location: {character.last_known_location}
Skills: {character.get_skills_string()}

World context: {world_context}
Threat type: {threat_type}
World state: {world_state}

Time elapsed: {interval_minutes} minutes
Drama level: {drama_level.upper()}
Drama guidance: {drama_guidance}

Situation type: {situation_type.value}

Generate a 2-3 sentence situation description appropriate for the drama level.
- For mundane: quiet moments, small tasks, simple observations
- For minor: brief encounters, small discoveries, easy choices
- For meaningful: real challenges, important decisions, notable events
- For major: combat, life-or-death choices, pivotal moments

Be specific and vivid. Match the scale to the time elapsed.

Format:
SITUATION: [description]
OPTIONS:
1. [option]
2. [option]
3. [option]
DIFFICULTY: [1-{max_difficulty}]
REWARDS: [potential gains]
RISKS: [potential dangers]
"""
            try:
                response = await self.dm_generate(prompt)
                return self._parse_situation(response, situation_type)
            except Exception as e:
                dbg.error("background", f"Failed to generate situation: {e}")

        # Fallback: generate a simple situation
        return self._generate_fallback_situation(character, situation_type)

    def _parse_situation(self, response: str, situation_type: SituationType) -> BackgroundSituation:
        """Parse a generated situation from the DM response."""
        description = ""
        options = []
        difficulty = 5
        rewards = []
        risks = []

        lines = response.strip().split('\n')
        current_section = None

        for line in lines:
            line = line.strip()
            if line.startswith("SITUATION:"):
                description = line[10:].strip()
                current_section = "situation"
            elif line.startswith("OPTIONS:"):
                current_section = "options"
            elif line.startswith("DIFFICULTY:"):
                try:
                    difficulty = int(line[11:].strip().split()[0])
                except:
                    pass
                current_section = None
            elif line.startswith("REWARDS:"):
                rewards = [r.strip() for r in line[8:].split(',')]
                current_section = None
            elif line.startswith("RISKS:"):
                risks = [r.strip() for r in line[6:].split(',')]
                current_section = None
            elif current_section == "situation" and line:
                description += " " + line
            elif current_section == "options" and line:
                # Remove numbering
                if line[0].isdigit() and len(line) > 2:
                    line = line[2:].strip()
                if line.startswith('.'):
                    line = line[1:].strip()
                if line:
                    options.append(line)

        # Ensure we have at least some options
        if not options:
            options = ["Take careful action", "Wait and observe", "Move to a different area"]

        return BackgroundSituation(
            situation_type=situation_type,
            description=description or "A moment of uncertainty in the wasteland.",
            options=options[:3],
            difficulty=min(10, max(1, difficulty)),
            potential_rewards=rewards,
            potential_risks=risks,
            time_pressure=random.random() < 0.3,
        )

    def _generate_fallback_situation(
        self,
        character: PlayerCharacter,
        situation_type: SituationType
    ) -> BackgroundSituation:
        """Generate a simple fallback situation without AI."""
        templates = {
            SituationType.SCAVENGE: BackgroundSituation(
                situation_type=situation_type,
                description=f"{character.character_name} spots what might be an untouched supply cache in a nearby structure.",
                options=["Investigate carefully", "Scout the perimeter first", "Mark location and continue"],
                difficulty=4,
                potential_rewards=["supplies", "tools"],
                potential_risks=["ambush", "structural collapse"],
                time_pressure=False,
            ),
            SituationType.SHELTER: BackgroundSituation(
                situation_type=situation_type,
                description=f"Night is falling. {character.character_name} needs to find shelter soon.",
                options=["Find high ground", "Look for an enclosed space", "Keep moving through the night"],
                difficulty=3,
                potential_rewards=["rest", "safety"],
                potential_risks=["exposure", "exhaustion"],
                time_pressure=True,
            ),
            SituationType.ENCOUNTER_HOSTILE: BackgroundSituation(
                situation_type=situation_type,
                description=f"Movement in the shadows. {character.character_name} is not alone.",
                options=["Prepare to fight", "Attempt to hide", "Make noise to scare it off"],
                difficulty=6,
                potential_rewards=["survival", "supplies from enemy"],
                potential_risks=["injury", "death", "alerting others"],
                time_pressure=True,
            ),
            SituationType.ENCOUNTER_NEUTRAL: BackgroundSituation(
                situation_type=situation_type,
                description=f"A stranger appears - armed but not immediately hostile. They're watching {character.character_name}.",
                options=["Approach peacefully", "Keep distance but acknowledge", "Slip away unnoticed"],
                difficulty=4,
                potential_rewards=["information", "potential ally"],
                potential_risks=["betrayal", "conflict"],
                time_pressure=False,
            ),
            SituationType.ENCOUNTER_FRIENDLY: BackgroundSituation(
                situation_type=situation_type,
                description=f"Voices. Human voices. They sound... normal. A small group, maybe traders or survivors.",
                options=["Call out to them", "Observe from hiding first", "Follow at a distance"],
                difficulty=3,
                potential_rewards=["allies", "trade", "information"],
                potential_risks=["deception", "competition"],
                time_pressure=False,
            ),
            SituationType.ENVIRONMENTAL: BackgroundSituation(
                situation_type=situation_type,
                description=f"The weather turns hostile. Rain, or maybe worse. {character.character_name} needs to adapt.",
                options=["Find cover immediately", "Push through it", "Use it as concealment to move"],
                difficulty=4,
                potential_rewards=["progress", "concealment"],
                potential_risks=["exposure", "visibility loss"],
                time_pressure=True,
            ),
            SituationType.DISCOVERY: BackgroundSituation(
                situation_type=situation_type,
                description=f"Something unusual catches {character.character_name}'s eye. This wasn't here before.",
                options=["Investigate thoroughly", "Note location for later", "Approach with extreme caution"],
                difficulty=3,
                potential_rewards=["information", "resources", "plot hook"],
                potential_risks=["trap", "time loss"],
                time_pressure=False,
            ),
            SituationType.REST: BackgroundSituation(
                situation_type=situation_type,
                description=f"A moment of quiet. {character.character_name} has a chance to rest and think.",
                options=["Rest but stay alert", "Take time to repair/maintain gear", "Use the time to plan next move"],
                difficulty=2,
                potential_rewards=["recovery", "clarity"],
                potential_risks=["lowered guard"],
                time_pressure=False,
            ),
            SituationType.MORAL_DILEMMA: BackgroundSituation(
                situation_type=situation_type,
                description=f"A choice that tests who {character.character_name} really is. No easy answer.",
                options=["Follow instinct", "Consider the greater good", "Protect self-interest"],
                difficulty=5,
                potential_rewards=["self-knowledge", "allies or enemies made"],
                potential_risks=["regret", "consequences"],
                time_pressure=False,
            ),
        }

        return templates.get(situation_type, templates[SituationType.REST])

    async def _get_character_response(
        self,
        character: PlayerCharacter,
        situation: BackgroundSituation
    ) -> str:
        """Get the character's response to the situation based on their personality."""

        if self.ollama_generate:
            # Use AI to generate in-character response
            priorities = character.get_priorities()
            priority_str = " > ".join(p.value for p in priorities)

            prompt = f"""You are {character.character_name}, facing a situation alone in a hostile world.

Your personality:
- Alignment priorities: {priority_str}
- Current drive: {character.current_drive.value}
- Role: {character.role.value}
- Skills: {character.get_skills_string()}
{f'- Personal note: "{character.understudy_note}"' if character.understudy_note else ''}

Current state:
- Condition: {character.condition}
- Supplies: {character.supplies_status}
- Morale: {character.morale}

SITUATION:
{situation.description}

Your options:
1. {situation.options[0]}
2. {situation.options[1] if len(situation.options) > 1 else 'Wait'}
3. {situation.options[2] if len(situation.options) > 2 else 'Retreat'}

What do you do? Respond in first person, 2-3 sentences describing your action and reasoning.
Stay in character. Be decisive."""

            try:
                response = await self.ollama_generate(prompt)
                return response.strip()
            except Exception as e:
                dbg.error("background", f"Failed to get character response: {e}")

        # Fallback: choose based on alignment traits
        return self._choose_fallback_response(character, situation)

    def _choose_fallback_response(
        self,
        character: PlayerCharacter,
        situation: BackgroundSituation
    ) -> str:
        """Choose a response based on character traits without AI."""
        # Use alignment tendencies to pick an option
        risk_tolerance = character.get_alignment_tendency("take_risks")

        if situation.time_pressure:
            # Under pressure, lean toward first option (usually action)
            if random.random() < 0.6 + (risk_tolerance * 0.3):
                chosen = situation.options[0]
            else:
                chosen = situation.options[1] if len(situation.options) > 1 else situation.options[0]
        else:
            # No pressure, more thoughtful choice
            if risk_tolerance > 0.6:
                chosen = situation.options[0]  # Bold choice
            elif risk_tolerance < 0.4:
                chosen = situation.options[-1]  # Cautious choice
            else:
                chosen = random.choice(situation.options)

        return f"I decide to: {chosen}"

    async def _resolve_outcome(
        self,
        character: PlayerCharacter,
        situation: BackgroundSituation,
        response: str
    ) -> BackgroundTickResult:
        """Resolve the outcome of the character's response."""

        # Calculate success based on difficulty and character state
        base_success_chance = 0.7 - (situation.difficulty * 0.05)

        # Modify by condition
        condition_modifier = {
            "healthy": 0.1,
            "tired": 0.0,
            "injured": -0.15,
            "critical": -0.3,
            "incapacitated": -0.5,
        }.get(character.condition, 0)

        # Check for relevant skills
        skill_bonus = 0
        for skill in character.skills:
            skill_lower = skill.lower()
            if any(word in response.lower() for word in skill_lower.split()):
                skill_bonus = 0.15
                break

        success_chance = base_success_chance + condition_modifier + skill_bonus
        success = random.random() < success_chance

        # Generate outcome
        if self.dm_generate:
            prompt = f"""Resolve this survival situation outcome.

Character: {character.character_name}
Situation: {situation.description}
Character's response: {response}
Success: {"Yes" if success else "No"}
Difficulty: {situation.difficulty}/10

Write a 2-3 sentence outcome description. Be specific about what happens.
If success: describe how they succeeded and any gains.
If failure: describe complications but keep them alive unless difficulty was 8+.

Also note any changes:
- Condition change? (healthy/tired/injured/critical)
- Supplies change? (found/lost/none)
- Morale change? (up/down/stable)
- Any discovery made?
- Any new ally or enemy?

Format:
OUTCOME: [description]
CONDITION: [new condition or "unchanged"]
SUPPLIES: [change or "unchanged"]
MORALE: [change or "unchanged"]
DISCOVERY: [if any, or "none"]
ALLY: [if any, or "none"]
ENEMY: [if any, or "none"]
"""
            try:
                dm_response = await self.dm_generate(prompt)
                return self._parse_outcome(character, situation, response, dm_response, success)
            except Exception as e:
                dbg.error("background", f"Failed to resolve outcome: {e}")

        # Fallback resolution
        return self._generate_fallback_outcome(character, situation, response, success)

    def _parse_outcome(
        self,
        character: PlayerCharacter,
        situation: BackgroundSituation,
        response: str,
        dm_response: str,
        success: bool
    ) -> BackgroundTickResult:
        """Parse the DM's outcome response."""
        outcome = ""
        condition_change = None
        supplies_change = None
        morale_change = None
        discovery = None
        ally = None
        enemy = None

        for line in dm_response.strip().split('\n'):
            line = line.strip()
            if line.startswith("OUTCOME:"):
                outcome = line[8:].strip()
            elif line.startswith("CONDITION:"):
                val = line[10:].strip().lower()
                if val != "unchanged":
                    condition_change = val
            elif line.startswith("SUPPLIES:"):
                val = line[9:].strip().lower()
                if val != "unchanged":
                    supplies_change = val
            elif line.startswith("MORALE:"):
                val = line[7:].strip().lower()
                if val != "unchanged":
                    morale_change = val
            elif line.startswith("DISCOVERY:"):
                val = line[10:].strip()
                if val.lower() != "none":
                    discovery = val
            elif line.startswith("ALLY:"):
                val = line[5:].strip()
                if val.lower() != "none":
                    ally = val
            elif line.startswith("ENEMY:"):
                val = line[6:].strip()
                if val.lower() != "none":
                    enemy = val

        return BackgroundTickResult(
            character_id=character.player_id,
            character_name=character.character_name,
            situation=situation,
            response=response,
            outcome=outcome or ("Success." if success else "Things didn't go as planned."),
            condition_change=condition_change,
            supplies_change=supplies_change,
            morale_change=morale_change,
            discovery=discovery,
            encounter_survived=situation.situation_type == SituationType.ENCOUNTER_HOSTILE and success,
            new_ally=ally,
            new_enemy=enemy,
        )

    def _generate_fallback_outcome(
        self,
        character: PlayerCharacter,
        situation: BackgroundSituation,
        response: str,
        success: bool
    ) -> BackgroundTickResult:
        """Generate a simple fallback outcome without AI."""
        if success:
            outcome = f"{character.character_name} handled the situation well."
            condition_change = None
            morale_change = "stable"

            # Small chance of improvement
            if situation.situation_type == SituationType.REST:
                if character.condition == "tired":
                    condition_change = "healthy"
                elif character.condition == "injured":
                    condition_change = "tired"

            if situation.situation_type == SituationType.SCAVENGE:
                supplies_change = "found supplies"
            else:
                supplies_change = None

            discovery = None
            if situation.situation_type == SituationType.DISCOVERY:
                discovery = "Found something worth remembering"

        else:
            outcome = f"{character.character_name} faced difficulties but pushed through."
            condition_change = None
            supplies_change = None
            morale_change = "down"
            discovery = None

            # Risk of injury in hostile encounters
            if situation.situation_type == SituationType.ENCOUNTER_HOSTILE:
                if random.random() < 0.4:
                    if character.condition == "healthy":
                        condition_change = "injured"
                    elif character.condition == "injured":
                        condition_change = "critical"

        return BackgroundTickResult(
            character_id=character.player_id,
            character_name=character.character_name,
            situation=situation,
            response=response,
            outcome=outcome,
            condition_change=condition_change,
            supplies_change=supplies_change,
            morale_change=morale_change,
            discovery=discovery,
            encounter_survived=situation.situation_type == SituationType.ENCOUNTER_HOSTILE and success,
            new_ally=None,
            new_enemy=None,
        )

    def _apply_result(self, character: PlayerCharacter, result: BackgroundTickResult, room_id: str = ""):
        """
        Apply the result to update character state.

        FULL SIMULATION: Also updates real inventory/condition/fatigue trackers.
        """
        char_inv_id = f"sep_{character.player_id}"

        # === UPDATE CONDITION (with real tracker) ===
        if result.condition_change:
            print(f"    >>> CONDITION CHANGE: {result.condition_change}")
            character.update_condition(result.condition_change, result.outcome[:50])

            # Also update real condition tracker
            if HAS_CONDITION:
                try:
                    condition_tracker = get_condition_tracker()
                    char_condition = condition_tracker.get_or_create(char_inv_id)
                    if char_condition:
                        if result.condition_change == "injured":
                            print(f"        Adding injury to tracker: Injury from {result.situation.situation_type.value}")
                            char_condition.add_injury(Injury(
                                description=f"Injury from: {result.situation.situation_type.value}",
                                severity=InjurySeverity.MODERATE,
                                timestamp=datetime.now().isoformat()
                            ))
                            char_condition.overall_condition = OverallCondition.WOUNDED
                        elif result.condition_change == "critical":
                            print(f"        Adding SEVERE injury to tracker!")
                            char_condition.add_injury(Injury(
                                description=f"Severe injury from: {result.situation.situation_type.value}",
                                severity=InjurySeverity.SEVERE,
                                timestamp=datetime.now().isoformat()
                            ))
                            char_condition.overall_condition = OverallCondition.CRITICAL
                        elif result.condition_change == "rested":
                            # Resting improves condition slightly
                            if char_condition.overall_condition == OverallCondition.SCRATCHED_UP:
                                print(f"        Rest healed scratches -> healthy")
                                char_condition.overall_condition = OverallCondition.HEALTHY
                        condition_tracker._save()
                except Exception as e:
                    print(f"        Condition tracker error: {e}")

        # === UPDATE SUPPLIES (with real inventory) ===
        if result.supplies_change:
            # Update simple status tracking
            if "found" in result.supplies_change.lower() or "gain" in result.supplies_change.lower():
                if character.supplies_status == "critical":
                    character.supplies_status = "low"
                elif character.supplies_status == "low":
                    character.supplies_status = "adequate"
                elif character.supplies_status == "adequate":
                    character.supplies_status = "abundant"

                # Also add item to real inventory
                if HAS_INVENTORY:
                    try:
                        inventory_tracker = get_inventory_tracker()
                        char_inv = inventory_tracker.get_inventory(char_inv_id)
                        if char_inv:
                            # Generate a scavenged item based on situation
                            item_name, item_cat = self._generate_scavenged_item(result.situation)
                            new_item = Item(
                                id="",  # Will be auto-generated
                                name=item_name,
                                category=item_cat,
                                description=f"Found during: {result.situation.description[:50]}",
                                acquired_from=f"Scavenged while separated",
                            )
                            char_inv.add_item(new_item)
                            inventory_tracker._save()
                            print(f"    >>> INVENTORY: Found {item_name} ({item_cat.value})")
                    except Exception as e:
                        print(f"        Inventory error: {e}")

            elif "lost" in result.supplies_change.lower() or "used" in result.supplies_change.lower():
                print(f"    >>> SUPPLIES LOST/USED")
                if character.supplies_status == "abundant":
                    character.supplies_status = "adequate"
                elif character.supplies_status == "adequate":
                    character.supplies_status = "low"
                elif character.supplies_status == "low":
                    character.supplies_status = "critical"

        # === UPDATE MORALE ===
        if result.morale_change:
            old_morale = character.morale
            if "up" in result.morale_change.lower() or "high" in result.morale_change.lower():
                if character.morale == "broken":
                    character.morale = "low"
                elif character.morale == "low":
                    character.morale = "stable"
                elif character.morale == "stable":
                    character.morale = "high"
            elif "down" in result.morale_change.lower() or "low" in result.morale_change.lower():
                if character.morale == "high":
                    character.morale = "stable"
                elif character.morale == "stable":
                    character.morale = "low"
                elif character.morale == "low":
                    character.morale = "broken"
            if old_morale != character.morale:
                print(f"    >>> MORALE: {old_morale} -> {character.morale}")

        # === HANDLE REST (recover fatigue) ===
        if result.situation.situation_type == SituationType.REST and result.condition_change == "rested":
            if HAS_FATIGUE:
                try:
                    fatigue_tracker = get_fatigue_tracker()
                    char_fatigue = fatigue_tracker.get_or_create_fatigue(char_inv_id, character.character_name)
                    if char_fatigue:
                        # Rest for a few hours
                        rest_hours = random.uniform(2, 4)
                        char_fatigue.hours_awake = max(0, char_fatigue.hours_awake - rest_hours * 2)
                        # Recalculate level
                        if char_fatigue.hours_awake < 12:
                            char_fatigue.fatigue_level = FatigueLevel.RESTED
                        elif char_fatigue.hours_awake < 18:
                            char_fatigue.fatigue_level = FatigueLevel.FINE
                        fatigue_tracker._save()
                        dbg.info("background", f"{character.character_name} rested, fatigue reduced")
                except Exception as e:
                    dbg.error("background", f"Failed to update fatigue for rest: {e}")

        # === HANDLE FOOD/WATER FOUND (improve hunger/thirst) ===
        if result.supplies_change and "found" in result.supplies_change.lower():
            if HAS_CONDITION:
                try:
                    condition_tracker = get_condition_tracker()
                    char_condition = condition_tracker.get_or_create(char_inv_id)
                    if char_condition:
                        # Small chance of finding food/water
                        if random.random() < 0.3:  # 30% chance supplies include food
                            char_condition.hunger = char_condition.hunger.improve()
                            dbg.info("background", f"{character.character_name} ate, now {char_condition.hunger.value}")
                        if random.random() < 0.4:  # 40% chance supplies include water
                            char_condition.thirst = char_condition.thirst.improve()
                            dbg.info("background", f"{character.character_name} drank, now {char_condition.thirst.value}")
                        condition_tracker._save()
                except Exception as e:
                    dbg.error("background", f"Failed to improve hunger/thirst: {e}")

        # === RECORD DISCOVERY ===
        if result.discovery:
            print(f"    >>> DISCOVERY: {result.discovery[:80]}...")
            character.add_discovery(result.discovery)

        # === RECORD ENCOUNTER ===
        if result.situation.situation_type == SituationType.ENCOUNTER_HOSTILE:
            survived_str = "SURVIVED" if result.encounter_survived else "FAILED"
            print(f"    >>> HOSTILE ENCOUNTER: {survived_str}")
            character.record_encounter(result.encounter_survived, result.outcome)

        # === RECORD ALLY/ENEMY ===
        if result.new_ally:
            print(f"    >>> NEW ALLY: {result.new_ally}")
            character.allies_met.append(result.new_ally)
            if len(character.allies_met) > 10:
                character.allies_met = character.allies_met[-10:]

        if result.new_enemy:
            print(f"    >>> NEW ENEMY: {result.new_enemy}")
            character.enemies_made.append(result.new_enemy)
            if len(character.enemies_made) > 10:
                character.enemies_made = character.enemies_made[-10:]

        # === ADD JOURNAL ENTRY ===
        severity = "minor"
        if result.condition_change in ["injured", "critical"]:
            severity = "major"
        if result.encounter_survived:
            severity = "notable"
        if result.discovery:
            severity = "notable"

        print(f"    >>> JOURNAL ENTRY ({severity}): {result.situation.situation_type.value}")
        character.add_journal_entry(
            event_type=result.situation.situation_type.value,
            description=f"{result.situation.description[:100]}... → {result.outcome[:100]}",
            severity=severity,
        )

    def _generate_scavenged_item(self, situation: BackgroundSituation) -> tuple:
        """Generate a random scavenged item based on situation type."""
        # Common scavenge items for survival scenarios
        scavenge_items = [
            ("Canned food", ItemCategory.CONSUMABLE),
            ("Water bottle", ItemCategory.CONSUMABLE),
            ("First aid supplies", ItemCategory.CONSUMABLE),
            ("Flashlight", ItemCategory.TOOL),
            ("Rope", ItemCategory.TOOL),
            ("Knife", ItemCategory.WEAPON),
            ("Matches", ItemCategory.TOOL),
            ("Bandages", ItemCategory.CONSUMABLE),
            ("Granola bars", ItemCategory.CONSUMABLE),
            ("Batteries", ItemCategory.MISC),
            ("Tarp", ItemCategory.TOOL),
            ("Duct tape", ItemCategory.TOOL),
        ]

        # Weight toward consumables for survival
        if situation.situation_type == SituationType.SCAVENGE:
            consumables = [i for i in scavenge_items if i[1] == ItemCategory.CONSUMABLE]
            if random.random() < 0.6:
                return random.choice(consumables)

        return random.choice(scavenge_items)


# =============================================================================
# Background Tick Scheduler
# =============================================================================

class BackgroundTickScheduler:
    """
    Manages periodic background ticks for all separated characters in a room.

    interval_minutes affects event drama:
    - < 5 min: Mundane events (resting, walking, small observations)
    - 5-30 min: Minor events (found something, brief encounter)
    - 30-60 min: Meaningful events (decisions, discoveries, challenges)
    - 60+ min: Major events (combat, significant choices, big changes)
    """

    def __init__(
        self,
        room_id: str,
        world_context: str = "",
        threat_type: str = "",
        world_state: str = "",
    ):
        self.room_id = room_id
        self.world_context = world_context
        self.threat_type = threat_type
        self.world_state = world_state
        self.processor: Optional[BackgroundTickProcessor] = None
        self._running = False
        self.interval_minutes = 30  # Default, can be updated before processing

    def set_processor(self, processor: BackgroundTickProcessor):
        """Set the tick processor."""
        self.processor = processor

    async def process_all_pending(self) -> List[BackgroundTickResult]:
        """Process all characters that need a background tick."""
        if not self.processor:
            return []

        tracker = get_autopilot_tracker()
        results = []

        for character in tracker.get_characters_needing_tick(self.room_id):
            try:
                result = await self.processor.process_tick(
                    character,
                    self.world_context,
                    self.threat_type,
                    self.world_state,
                    interval_minutes=self.interval_minutes,
                    room_id=self.room_id,  # Pass room_id for tracker access
                )
                if result:
                    results.append(result)
            except Exception as e:
                dbg.error("background", f"Failed to process tick for {character.character_name}: {e}")

        # Save after processing all
        tracker._save()

        return results

    async def run_loop(self, check_interval_seconds: int = 60):
        """Run a continuous loop checking for characters needing ticks."""
        self._running = True
        dbg.info("background", f"Starting background tick loop for room {self.room_id}")

        while self._running:
            try:
                results = await self.process_all_pending()
                if results:
                    dbg.info("background", f"Processed {len(results)} background ticks")
            except Exception as e:
                dbg.error("background", f"Error in background tick loop: {e}")

            await asyncio.sleep(check_interval_seconds)

    def stop(self):
        """Stop the background tick loop."""
        self._running = False
        dbg.info("background", f"Stopping background tick loop for room {self.room_id}")


# =============================================================================
# Global scheduler registry
# =============================================================================

_schedulers: Dict[str, BackgroundTickScheduler] = {}


def get_scheduler(room_id: str) -> Optional[BackgroundTickScheduler]:
    """Get the scheduler for a room."""
    return _schedulers.get(room_id)


def create_scheduler(
    room_id: str,
    world_context: str = "",
    threat_type: str = "",
    world_state: str = "",
) -> BackgroundTickScheduler:
    """Create a new scheduler for a room."""
    scheduler = BackgroundTickScheduler(
        room_id=room_id,
        world_context=world_context,
        threat_type=threat_type,
        world_state=world_state,
    )
    _schedulers[room_id] = scheduler
    return scheduler


def remove_scheduler(room_id: str):
    """Remove a scheduler for a room."""
    if room_id in _schedulers:
        _schedulers[room_id].stop()
        del _schedulers[room_id]
